### ISSUE TITLE
Add tags for task 2311 when updated by leetcode

### ISSUE THREAD

**Issue by AryamanMishra** [javadev/LeetCode-in-Java#1192]
Update solution with tags when given by leetcode

**Comment by javadev** [comment]
Hi @AryamanMishra,

Thank you for the issue.

The routine to generate tags is not scan a page for now. It uses predefined values that need to be updated.

I uploaded newest version generatemd tool with latests tags.

**Comment by javadev** [comment]
Additional tasks will be included.
